# Generated by Django 5.2.8 on 2025-12-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('aforo_max', models.PositiveIntegerField(default=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AforoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aforo', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='aforo.local')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
